#!/usr/bin/env ruby
#require File.dirname(__FILE__) + '/../vendor/plugins/script-refactor/lib/script_refactor'
require '~/Desktop/rails_dev/project1/vendor/plugins/script-refactor/lib/script_refactor'
